### ISSUE TITLE
Remove an entire category of items?

### ISSUE THREAD

**Issue by Samistine** [RegalOwl/HyperConomy#103]
I am not sure how we are suppose to go about disabling types of items in an economy.
For a lot of servers, admins don't want mobeggs being sold/bought, in this example how would one remove anything to do with mobeggs?

**Comment by Aberzhulan** [comment]
Type /ss rcat <category>

For a list of categories, you can type /listcategories.

**Comment by RegalOwl** [comment]
If you want to completely remove an item you can easily do that with the GUI.  Just double click HyperConomy.jar, edit your economy, and delete the items you don't want.  You can sort by category so this should be easy.  If you'd like to preserve the items for the future clone or make a new economy and edit that one instead of the default.
