### ISSUE TITLE
display items on signs

### ISSUE THREAD

**Issue by jonny42g** [RegalOwl/HyperConomy#69]
place a sign then place a sign on top on that sign and fly above the two signs make display then break the bottom sign then try to remove the display it will say there was no display detected  

please fix

**Comment by RegalOwl** [comment]
Fly over the place where the display is and type "/rdis u".  That command will remove any display in your vertical block column.  That should remove it.  There isn't really a way to fix this that I know of since the display feature relies on looking at the block that the display is on.  Since it's a sign that's been destroyed your player can no longer look at it.
