### ISSUE TITLE
Categories.yml?

### ISSUE THREAD

**Issue by Wilberforce77** [RegalOwl/HyperConomy#85]
I was reading about categories on the wiki.

This page:
https://github.com/RegalOwl/HyperConomy-Documentation/blob/master/Wiki/Shops/Server%20Shops.creole

And I can't find categories.yml in the plugin folder. I would love to know how to add and edit my own categories for my shops!

**Comment by RegalOwl** [comment]
I need to remove that reference.  Categories.yml has been moved into the database.  It's actually easier to edit now than before.  Just make a local copy of your database and double click the HyperConomy.jar file to open the GUI. (Not the Lite version.)  Categories can easily be created and items can easily be moved in and out of categories.  After you've made the changes that you'd like upload your HyperConomy.db file to your server.  If you're using MySQL you may be able to connect directly to your server's database depending on your server configuration.

**Comment by Wilberforce77** [comment]
Oh nice! That looks really good! I'm pretty sure my MySql server is working with hyper. I have my own server machine in my garage. The mysql server is managed though webmin for debian. I'm not sure how to create a new database for hyper or how I would import and export it to edit it on my pc. Also, I don't even know what's better about using a mysql server over the db file in the plugin folder.

Any of you advice is greatly appreciated! Sorry for all the noob-ness!


Date: Fri, 7 Aug 2015 17:39:58 -0700

**Comment by RegalOwl** [comment]
The advantage of MySQL is that you can connect to it remotely if you enable that in the MySQL config.  It's also more reliable since it allows concurrent writes.  This means you can edit the database while your server is running without causing any major issue.  (You'll need to disable and then reenable HyperConomy for any database changes to take affect.)  So to edit your server's HyperConomy remotely you can download HyperConomy.jar onto your PC and then run it.  Shut it down after loading it once so it generates the config file.  Then enable MySQL and point the MySQL configuration in the new config.yml file to your remote MySQL server.  (The IP of the server and default MySQL port will probably work.)  The only issue is that remote connections might not be allowed to MySQL so you might need to allow that in the mysql config on your server.

You can also just export the data from HyperConomy.  In game run the command /hcdata exportcsv all  This will create an import_export folder in your HyperConomy folder.  Download that folder onto your computer and run a local Minecraft server with HyperConomy.  Paste the import_export folder into your local server and then run the command /hcdata importcsv all.  This will copy whatever was in your MySQL database into your local database.  It's fine if you use the HyperConomy.db SQLite database locally.  Edit whatever you like with the GUI after that and then reexport your database from the local server and replace the import_export folder on the remote server with your edited database.  On the real server then run the command /hcdata importcsv all.  

In the future I'll see if I can make it easier to edit remote servers with the GUI.  It's not too bad once you get the hang of it.  It's especially easy if your MySQL server allows remote connections.
