### ISSUE TITLE
CRITICAL BUG - Players can get an unlimited number of enchanted books

### ISSUE THREAD

**Issue by DKrolls** [RegalOwl/HyperConomy#87]
![protectioniii](https://cloud.githubusercontent.com/assets/12780812/10036444/7dcc3b6a-616d-11e5-9a31-488a89767dd9.PNG)
I am using version: hyperconomy-0.975.6-SNAPSHOT.jar (most recent)
I got the bug by: Creating a 1x1 shop, then adding a Protection III enchantment off a Protection III Sharpness III enchanted book. Then, when holding a stack of 40+ regular books, I did /ms remove protection_3 1, and the entire stack of books became enchanted. Please fix this bug ASAP, as it can wreck my server's economy. Thanks!

**Comment by RealSmileyguy** [comment]
I was able to find a temporary way to disable enchantments, via removing the books from my players' shops and putting them somewhere safe, disabling the plugin, running an SQL query to remove all elements of type ENCHANTMENT before saving and re-enabling hyperconomy. If you find that this bug is too difficult to solve right away, please at least add an option to disable the buying/selling of enchanted books. Thanks.

**Comment by RegalOwl** [comment]
Thanks for reporting this.  I will be working on a fix.

**Comment by DKrolls** [comment]
Excellent, thank you!

**Comment by RegalOwl** [comment]
This should be fixed in the latest dev build.

**Comment by DKrolls** [comment]
I'll try it ASAP.
